version: '3'
services:
                    #### API #### 
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - network_api
    depends_on: 
      - db_api

                    #### DATABASE #### 
  db_api:
    image: mysql:8.0
    container_name: db_api
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - network_api
    volumes:
      - database_api:/var/lib/mysql

                    #### NETWORKS #### 
networks:
  network_api:
    driver: bridge

                    #### VOLUMES #### 
volumes:
  database_api:
    driver: local