version: '3'
services:
                    #### DATABASE #### 

  db_api:
    image: mysql:8.0
    container_name: db_api
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - network_api
    volumes:
      - database_api:/var/lib/mysql
    ports:
      - "3306:3306"

                          #### API #### 
  api:
    depends_on: 
      - db_api
    container_name: api
    restart: unless-stopped
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db_api/3306; do sleep 1; done; npm start'
    ports:
      - "8000:8000"
    networks:
      - network_api



                    #### NETWORKS #### 
networks:
  network_api:
    driver: bridge

                    #### VOLUMES #### 
volumes:
  database_api:
    driver: local